apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  pacman-github-ci-listener
  name: pacman-github-ci-prod-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-pacman-github-ci-prod-listener
