apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  chris-ui-github-ci-listener
  name: chris-ui-github-ci-prod-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-chris-ui-github-ci-prod-listener
