apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: chris-ui-github-ci-prod-listener
spec:
  serviceAccountName: chris-ui-ci-pipeline
  triggers:
    - name: github-prod-listener
      bindings:
        - ref: chris-ui-ci-pipeline-prod-binding
      template:
        ref: chris-ui-ci-trigger-pipeline-prod-template
