apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  cube-github-ci-listener
  name: cube-github-ci-prod-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-cube-github-ci-prod-listener
