apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cube-github-ci-prod-listener
spec:
  serviceAccountName: cube-ci-pipeline
  triggers:
    - name: github-prod-listener
      bindings:
        - ref: cube-ci-pipeline-prod-binding
      template:
        ref: cube-ci-trigger-pipeline-prod-template
