apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cube-ci-trigger-pipeline-prod-template
spec:
  params:
  - name: docker_url
  - name: tag
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cube-ci-prod-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: cube-ci-pipeline-production
      params:
        - name: repo_type
          value: github.com
        - name: cube-cd-git-url
          value: gitopsify/cube-cd
        - name: cube-cd-git-repo-name
          value: cube-cd
        - name: cube-cd-git-repo-path-to-content
          value: env/03-production
        - name: cube-cd-git-repo-branch
          value: "production-ready"
        - name: cube-cd-git-target-branch-pr
          value: "production"
        - name: cube-cd-git-commit-comment
          value: "Update from ci process - production"
        - name: cube-cd-git-user-name
          value: "Raghuram Banda"
        - name: cube-cd-git-user-email
          value: "rbanda@redhat.com"
        - name: acs_central_endpoint
          value: acs-secret
        - name: acs_api_token
          value: acs-secret
        - name: roxctl-output-format
          value: "table"
        - name: recursive-search
          value: "true"
        - name: image
          value: $(tt.params.docker_url):$(tt.params.tag)
      workspaces:
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
