apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cube-github-ci-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      bindings:
        - ref: cube-ci-pipeline-binding
      template:
        ref: cube-ci-trigger-pipeline-template