apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: chris-ui-github-ci-listener
spec:
  serviceAccountName: chris-ui-ci-pipeline
  triggers:
    - name: github-listener
      bindings:
        - ref: chris-ui-ci-pipeline-binding
      template:
        ref: chris-ui-ci-trigger-pipeline-template