apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pacman-ci-trigger-pipeline-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrepository.fullname
  - name: gitrevision
  - name: commit.prior_revision
  - name: commit.ref
  - name: commit.id
  - name: commit.date
  - name: commit.message
  - name: commit.author
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pacman-ci-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: pacman-ci-pipeline
      resources:
        - name: intermediate-image
          resourceRef:
            name: pacman-ci-intermediate
        - name: runtime-image
          resourceRef:
            name: pacman-runtime
      params:
        - name: STORAGE_DRIVER
          value: vfs   
        - name: openshift_app_name
          value: pacman-ci   
        - name: runtime_image_name
          value: pacman-runtime
        - name: runtime_base_image
          # - open-liberty-base:2 - bad image
          # - openliberty:10 - good image
    #      value: quay.io/marrober/open-liberty-base:2  
          value: quay.io/marrober/openliberty:latest  
        - name: repo_type
          value: github.com
        - name: pacman-cd-git-url 
          value: gitopsify/pacman-cd
        - name: pacman-cd-git-repo-name
          value: pacman-cd
        - name: pacman-cd-git-repo-path-to-content-development
          value: env/01-dev      
        - name: pacman-cd-git-repo-path-to-content-qa
          value: env/02-qa     
        - name: pacman-cd-git-repo-branch-qa
          value: "qa-ready"   
        - name: pacman-cd-git-target-branch-pr 
          value: "main"
        - name: pacman-cd-git-commit-comment-dev
          value: "Update from ci process - dev"
        - name: pacman-cd-git-commit-comment-qa
          value: "Update from ci process - qa"          
        - name: pacman-cd-git-user-name
          value: "Raghuram Banda"
        - name: pacman-cd-git-user-email
          value: "rbanda@redhat.com"
        - name: acs_central_endpoint
          value: acs-secret
        - name: acs_api_token
          value: acs-secret
        - name: roxctl-output-format
          value: "table"     
        - name: recursive-search
          value: "true"
        - name: quay-io-account
          value: "rbrhssa"
        - name: quay-io-repository
          value: "pacman"          
        - name: source-git-url
          value: $(tt.params.gitrepository.url)
        - name: gitrepository_fullname
          value: $(tt.params.gitrepository.fullname)
        - name: source-git-revision
          value: $(tt.params.gitrevision)
        - name: commit_prior_revision
          value: $(tt.params.commit.prior_revision)
        - name: commit_ref
          value: $(tt.params.commit.ref)
        - name: commit_id
          value: $(tt.params.commit.id)
        - name: commit_date
          value: $(tt.params.commit.date)
        - name: commit_message
          value: $(tt.params.commit.message)
        - name: commit_author
          value: $(tt.params.commit.author)
      workspaces:
      - name: files
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi  
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi

