apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: myApp-RuntimeResource
  namespace: liberty-rest
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/myapp-ci/myApp-RuntimeResource
  type: image 