apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: <source-code-app-name>
  namespace: <namespace>
  labels:
    ci-resources: group1
spec:
  params:
  - name: url
    value:
  type: git
