apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-chris-ui-base-image-
spec:
  pipelineRef:
    name: build-chris-ui-base-image
  params:
    - name: git-url
      value: https://github.com/gitopsify/chris-ui-ci.git
    - name: git-revision
      value: main
    - name: quay-io-account
      value: "fedora"
    - name: quay-io-repository
      value: "nodejs-16"
    - name: quay-io-image-tag-name
      value: "latest"
    - name: acs_central_endpoint
      value: acs-secret
    - name: acs_api_token
      value: acs-secret
    - name: roxctl-output-format
      value: "table"
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
