apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-base-image-pr-
spec:
  pipelineRef:
    name: build-base-image
  params:
    - name: git-url
      value: http://gogs.apps.skylake.demolab.local/mroberts/myApp-config.git
    - name: git-revision
      value: main   
    - name: quay-io-account
      value: "marrober"
    - name: quay-io-repository
      value: "openliberty"
    - name: quay-io-image-tag-name
      value: "latest"
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
