apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    pipeline.openshift.io/type: kubernetes
  name: myapp-cd-validation
  namespace: myapp-ci
spec:
  params:
  - name: resource-git-url              # CD content repository
    type: string
  - name: resource-git-revision         # Branch of the CD content repository
    type: string
  - name: deployment-asset-subdir       # Specific location of deployment assets in the CD repository
    type: string
  - name: acs_central_endpoint          # Advanced Cluster Security endpoint
    type: string
  - name: acs_api_token                 # Advanced Cluster Security access token secret
    type: string
  - name: recursive-search              # Search subdirectories of deployment assets
    type: string
  - name: roxctl-output-format          # Advanced Cluster Security image scan output format
    type: string
  tasks:
##------------------------------------------------------------------
# Git clone deployment assets code task
##------------------------------------------------------------------
  - name: git-clone-resources
    params:
    - name: url
      value: $(params.resource-git-url)
    - name: revision
      value: $(params.resource-git-revision)
    - name: verbose
      value: 'false'
    - name: subdirectory
      value: resources
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: files
##------------------------------------------------------------------
# Process kustomization file to generate deployment resources
##------------------------------------------------------------------
  - name: configure-deployment-assets
    params:
    - name: subdirectory
      value: $(params.deployment-asset-subdir)
    taskRef:
      kind: Task
      name: configure-deployment-assets
    runAfter:
    - git-clone-resources
    workspaces:
    - name: files
      workspace: files
##------------------------------------------------------------------
# Perform resource deployment check on files of interest
##------------------------------------------------------------------
  - name: resource-deployment-check
    params:
    - name: acs_central_endpoint
      value: $(params.acs_central_endpoint)
    - name: acs_api_token
      value: $(params.acs_api_token)
    - name: source_location
      value: $(params.deployment-asset-subdir)
    - name: recursive-search
      value: $(params.recursive-search)
    - name: roxctl-output-format
      value: $(params.roxctl-output-format)
    taskRef:
      kind: Task
      name: acs-deployment-check
    workspaces:
    - name: files
      workspace: files
    runAfter:
    - configure-deployment-assets
##------------------------------------------------------------------
# Add commit status to QA branch if the resource deployment check
# is successful
##------------------------------------------------------------------
  - name: set-commit-status
    params:
    - name: GIT_REPO
      value: $(params.myapp-cd-git-url)
    - name: REPO
      value: $(params.my-app-cd-git-repo-name)
    - name: GIT_TOKEN_SECRET_NAME
      value: github-access-token
    - name: GIT_TOKEN_SECRET_KEY
      value: token
    - name: COMMIT_SHA
      value: $(tasks.update-and-commit-kustomization-file-qa.results.commit-id)
    - name: DESCRIPTION
      value: "Pending status on commit to qa-ready"
    - name: CONTEXT
      value: "continuous-integration/Tekton"
    - name: STATE
      value: "success"
    taskRef:
      kind: Task
      name: set-commit-status
    when:
    - input: "$(tasks.resource-deployment-check.results.scan-result)"
      operator: in
      values:
      - "pass"
    runAfter:
      - resource-deployment-check
##------------------------------------------------------------------
# Workspace definition.
##------------------------------------------------------------------
  workspaces:
  - name: files
