apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    pipeline.openshift.io/type: kubernetes
  name: myapp-ci-pipeline-2
  namespace: myapp-ci
spec: 
  params:
  - name: acs_central_endpoint          # Advanced Cluster Security endpoint
    type: string
  - name: acs_api_token                 # Advanced Cluster Security access token secret
    type: string
  - name: roxctl-output-format          # Advanced Cluster Security image scan output format
    type: string  
  - name: image-url
    type: string
  tasks:
  - name: image-build-check
    params:
    - name: acs_central_endpoint
      value: $(params.acs_central_endpoint)
    - name: acs_api_token
      value: $(params.acs_api_token)
    - name: public-url
      value: $(params.image-url)
    - name: roxctl-output-format
      value: $(params.roxctl-output-format)        
    taskRef:
      kind: Task
      name: acs-image-build-check       
##------------------------------------------------------------------
# Workspace definition.
##------------------------------------------------------------------         
  workspaces:
  - name: files  

