apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    pipeline.openshift.io/type: kubernetes
  name: myapp-ci-pipeline
  namespace: myapp-ci
spec:
  resources:
  - name: intermediate-image
    type: image
  params:
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: source-git-url   
    type: string
  - name: source-git-revision
    type: string
  tasks:
##------------------------------------------------------------------
# Git clone source code task
##------------------------------------------------------------------
  - name: git-clone-source
    params:
    - name: url
      value: $(params.source-git-url)
    - name: revision
      value: $(params.source-git-revision)
    - name: verbose
      value: 'false'
    - name: subdirectory
      value: source
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: files    
##------------------------------------------------------------------
# Build application
##------------------------------------------------------------------      
  - name: build
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
    resources:
      outputs:
      - name: intermediate-image
        resource: intermediate-image
    taskRef:
      kind: Task
      name: build
    workspaces:
    - name: files
      workspace: files      
  workspaces:
  - name: files      
