apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    pipeline.openshift.io/type: kubernetes
  name: myapp-ci-pipeline
  namespace: myapp-ci
spec:
  resources:
  - name: intermediate-image
    type: image
  params:
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: source-git-url   
    type: string
  - name: source-git-revision
    type: string
  - name: gitrepository_fullname
    type: string
  - name: commit_prior_revision
    type: string
  - name: commit_date
    type: string
  - name: commit_author
    type: string    
  - name: openshift_app_name
    type: string
  - name: runtime_image_name
    type: string
  - name: runtime_base_image
    type: string 
  tasks:
##------------------------------------------------------------------
# Git clone source code task
##------------------------------------------------------------------
  - name: git-clone-source
    params:
    - name: url
      value: $(params.source-git-url)
    - name: revision
      value: $(params.source-git-revision)
    - name: verbose
      value: 'false'
    - name: subdirectory
      value: source
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: files    
##------------------------------------------------------------------
# Build application
##------------------------------------------------------------------      
  - name: build
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
    resources:
      outputs:
      - name: intermediate-image
        resource: intermediate-image
    taskRef:
      kind: Task
      name: build
    runAfter:
    - git-clone-source
    workspaces:
    - name: files
      workspace: files      
  workspaces:
  - name: files   
##------------------------------------------------------------------
# Create the runtime image from a base container image and
# deployable asset extracted from the builder container image.
##------------------------------------------------------------------
  - name: create-runtime-image
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: gitrepository_url
        value: $(params.source-git-url)
      - name: gitrepository_fullname
        value: $(params.gitrepository_fullname)
      - name: commit_prior_revision
        value: $(params.commit_prior_revision)
      - name: commit_reference_branch
        value: $(params.source-git-revision)
      - name: commit_date
        value: $(params.commit_date)
      - name: commit_author
        value: $(params.commit_author)
      - name: runtime_image_name
        value: $(params.runtime_image_name)
      - name: openshift_app_name
        value: $(params.openshift_app_name)
      - name: baseImage
        value: $(params.baseImage)
      - name: sourceCommitTag
        value: "$(tasks.git-clone-source.results.commit)"
      - name: pipelineRunName
        value: $(context.pipelineRun.name)
      - name: pipelineName
        value: $(context.pipeline.name)        
    resources:
      inputs:
      - name: intermediate-image
        resource: intermediate-image
      outputs:
      - name: runtime-image
        resource: runtime-image
    taskRef:
      kind: Task
      name: create-runtime-image
    runAfter:
    - build
    workspaces:
    - name: files
      workspace: files     
