apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  myapp-github-listener
  name: myapp-github-listener-el
spec:
  port:
    targetPort: listener
  to:
    kind: Service
    name: myapp-rest-github-listener