apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: chris-ui-ci-pipelines-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - configmaps
  verbs:
  - patch
  - get
  - create
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - argocds
  verbs:
  - get
  - create
  - patch
