apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pacman-ci-pipeline
  namespace: pacman-ci
secrets:
- name: github-access-token
- name: quay-auth-secret
- name: acs-secret
