apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chris-ui-ci-pipelines-service-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chris-ui-ci-pipelines-clusterrole
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: chris-ui-ci
