kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chris-ui-ci-pipeline-sa-edit-rolebinding
  namespace: 
subjects:
- kind: ServiceAccount
  name: pipeline
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io