apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cube-runtime
  namespace: cube-ci
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/cube-ci/cube-runtime
  type: image