apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: myapp-ci-pipeline-
  namespace: myapp-ci
spec:
  pipelineRef: 
    name: myapp-ci-pipeline
  resources:
    - name: intermediate-image
      resourceRef:
        name:  myapp-ci-imagestreamresource
  params: 
    - name: source-git-url   
      value: https://github.com/marrober/myApp-source.git
    - name: source-git-revision
      value: main
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi        