apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: myapp-ci-pipeline-
  namespace: myapp-ci
spec:
  pipelineRef: 
    name: myapp-ci-pipeline
  resources:
    - name: intermediate-image
      resourceRef:
        name:  myapp-ci-intermediate
    - name: runtime-image
      resourceRef:
        name: myapp-runtime      
  params: 
    - name: source-git-url   
      value: https://github.com/marrober/myApp-source.git
    - name: source-git-revision
      value: main
    - name: STORAGE_DRIVER
      value: vfs      
    - name: gitrepository_fullname
      value: ""
    - name: commit_prior_revision
      value: ""
    - name: commit_date
      value: ""
    - name: commit_author
      value: ""
    - name: openshift_app_name
      value: myapp-ci
    - name: runtime_image_name
      value: myapp-runtime
    - name: runtime_base_image
      # - open-liberty-base:2 - bad image
      # - openliberty:5 - good image
      value: quay.io/marrober/open-liberty-base:2  
#      value: quay.io/marrober/openliberty:5    
    - name: myapp-cd-git-url 
      value: marrober/myApp-cd.git
    - name: my-app-cd-git-repo-name
      value: myApp-cd
    - name: my-app-cd-git-repo-path-to-content-development
      value: env/overlays/01-dev      
    - name: my-app-cd-git-commit-comment
      value: "Update from ci process"
    - name: my-app-cd-git-user-name
      value: "Mark Roberts"
    - name: my-app-cd-git-user-email
      value: "mroberts@redhat.com"
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi        