apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName:
  name: myapp-ci-pipeline-
  namespace: myapp-ci
spec:
  pipelineRef:
    name:
  resources:
    - name: app-source
      resourceRef:
        name: myapp-ci-source
    - name: intermediate-image
      resourceRef:
        name:  myapp-ci-imagestreamresource