apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: myapp-ci-pipeline-2-
  namespace: myapp-ci
spec:
  pipelineRef: 
    name: myapp-ci-pipeline-2  
  params: 
    - name: acs_central_endpoint
      value: acs-secret
    - name: acs_api_token
      value: acs-secret
    - name: roxctl-output-format
      value: "table"   
    - name: image-url
      value: image-registry.openshift-image-registry.svc:5000/myapp-ci/myapp-runtime:705c-7gzr7     
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi                