apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: myapp-ci-pipeline-
  namespace: myapp-ci
spec:
  pipelineRef: 
    name: myapp-ci-pipeline
  resources:
    - name: app-source
      resourceRef:
        name: myapp-ci-source
    - name: intermediate-image
      resourceRef:
        name:  myapp-ci-imagestreamresource
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi        