apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-and-commit-kustomization-file
  namespace: myapp-ci
spec:
  params:
  - name: GIT_URL
    type: string
  - name: GIT_REPO_NAME
    type: string
  - name: GIT_PATH_TO_CONTENT
    type: string    
  - name: GIT_USER_NAME
    type: string
  - name: GIT_USER_EMAIL
    type: string
  - name: GIT_COMMIT_COMMENT
    type: string
  - name: IMAGE
    type: string
  steps:
  - name: update-ops-repo-with-imagetag
    env:
      - name: GITHOSTACCESSTOKEN
        valueFrom:
          secretKeyRef:
            key: "token"
            name: "git-host-access-token"
    image: quay.io/marrober/kustomize:latest
    script: >
      #!/bin/sh

      cd /workspace/files/

      git config --global user.email $(params.GIT_USER_EMAIL)

      git config --global user.name $(params.GIT_USER_NAME)

      git clone https://${GITHOSTACCESSTOKEN}@github.com/$(params.GIT_URL)

      echo "-----------------------------------------------------------------"

      echo "view content of directory"

      echo "-----------------------------------------------------------------"

      cd /workspace/files/$(params.GIT_REPO_NAME)/env/overlays/01-dev

      ls -al

      echo "-----------------------------------------------------------------"

      echo "Git status prior to making any changes"

      echo "-----------------------------------------------------------------"

      git status

      echo "-----------------------------------------------------------------"

      echo "File before change"
      
      echo "-----------------------------------------------------------------"      

      cat kustomization.yaml

      kustomize edit set image $(params.IMAGE)

      echo "-----------------------------------------------------------------"

      echo "File after change"
      
      echo "-----------------------------------------------------------------"      

      cat kustomization.yaml

      cd /workspace/files/$(params.GIT_REPO_NAME)

      echo "-----------------------------------------------------------------"

      echo "Git status after change"
      
      echo "-----------------------------------------------------------------"      

      git status

      echo "-----------------------------------------------------------------"

      echo "Git add"
      
      echo "-----------------------------------------------------------------"  

      git add .

      echo "-----------------------------------------------------------------"

      echo "Git commit"
      
      echo "-----------------------------------------------------------------"        

      git commit -m "$(params.GIT_COMMIT_COMMENT)"

      echo "-----------------------------------------------------------------"

      echo "Git push"
      
      echo "-----------------------------------------------------------------"        

      git push -u origin HEAD:main

  workspaces:
    - name: files