apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-namespace/cicd-namespace.yaml
- 02-rolebindings/argocd-admin.yaml
- 02-rolebindings/pipeline-service-account.yaml
- 02-rolebindings/pipeline-service-role.yaml
- 02-rolebindings/pipeline-service-rolebinding.yaml
- 03-image-streams/containerImageStream-RuntimeImage.yaml
- 04-resources/imageResource-Intermediate.yaml
- 04-resources/imageResource-Runtime.yaml
- 05-tasks/build-image.yaml
- 05-tasks/create-runtimeImage.yaml
- 05-tasks/update-and-commit-kustomization-file.yaml
- 06-pipeline/pipeline.yaml
- 06-pipeline/pipeline-2.yaml
