apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-pipeline/build-base-image-pipeline.yaml
- 03-tasks/build-push-base-image.yaml
- ../main-ci/05-tasks/acs-image-build-check.yaml
