apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-base-image
spec:
  params:
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: git-url
    type: string
  - name: git-revision
    type: string
  - name: quay-io-account
    type: string
  - name: quay-io-repository
    type: string
  - name: quay-io-image-tag-name
    type: string
    default: "latest"
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
  - name: git-clone-resources
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: verbose
      value: 'false'
    - name: subdirectory
      value: resources
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: files
##------------------------------------------------------------------
# Build the base image
##------------------------------------------------------------------
  - name: build-base-image
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: quay-io-account
        value: $(params.quay-io-account)
      - name: quay-io-repository
        value: $(params.quay-io-repository)
      - name: quay-io-image-tag-name
        value: $(params.quay-io-image-tag-name)
    taskRef:
      kind: Task
      name: build-push-base-image
    runAfter:
    - git-clone-resources
    workspaces:
    - name: files
      workspace: files
##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
  - name: files
