apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: chris-ui-ci-pipeline-
  namespace: chris-ui-ci
spec:
  pipelineRef:
    name: chris-ui-ci-pipeline
  resources:
    - name: intermediate-image
      resourceRef:
        name:  chris-ui-ci-intermediate
    - name: runtime-image
      resourceRef:
        name: chris-ui-runtime
  params:
    - name: source-git-url
      value: https://github.com/gitopsify/chris-ui.git
    - name: source-git-revision
      value: main
    - name: STORAGE_DRIVER
      value: vfs
    - name: gitrepository_fullname
      value: ""
    - name: commit_prior_revision
      value: ""
    - name: commit_date
      value: ""
    - name: commit_author
      value: ""
    - name: openshift_app_name
      value: chris-ui-ci
    - name: runtime_image_name
      value: chris-ui-runtime
    - name: runtime_base_image
      # - open-liberty-base:2 - bad image
      # - openliberty:10 - good image
#      value: quay.io/marrober/open-liberty-base:2
      value: quay.io/marrober/openliberty:latest
    - name: repo_type
      value: github.com
    - name: chris-ui-cd-git-url
      value: gitopsify/chris-ui-cd
    - name: chris-ui-cd-git-repo-name
      value: chris-ui-cd
    - name: chris-ui-cd-git-repo-path-to-content-development
      value: env/01-dev
    - name: chris-ui-cd-git-repo-path-to-content-qa
      value: env/02-qa
    - name: chris-ui-cd-git-repo-branch-qa
      value: "qa-ready"
    - name: chris-ui-cd-git-target-branch-pr
      value: "main"
    - name: chris-ui-cd-git-commit-comment-dev
      value: "Update from ci process - dev"
    - name: chris-ui-cd-git-commit-comment-qa
      value: "Update from ci process - qa"
    - name: chris-ui-cd-git-user-name
      value: "Raghuram Banda"
    - name: chris-ui-cd-git-user-email
      value: "rbanda@redhat.com"
    - name: acs_central_endpoint
      value: acs-secret
    - name: acs_api_token
      value: acs-secret
    - name: roxctl-output-format
      value: "table"
    - name: recursive-search
      value: "true"
    - name: quay-io-account
      value: "rbrhssa"
    - name: quay-io-repository
      value: "chris-ui"
    - name: production-event-listener-route
      value: http://chris-ui-github-ci-prod-listener-chris-ui-ci.apps.cluster-54m5x.54m5x.sandbox472.opentlc.com
    - name: demolab
      value: "no"
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
